### ISSUE TITLE
Uncaught Error: Class "ComposerUnused\ComposerUnused\Di\ServiceContainer" not found in phar

### ISSUE THREAD

**Issue by icanhazstring** [composer-unused/composer-unused-plugin#2]
Executing `composer unused` throws an exception that a class can not be found inside phar

```
PHP Fatal error:  Uncaught Error: Class "ComposerUnused\ComposerUnused\Di\ServiceContainer" not found in phar:///Users/andreas.froemer/Projects/composer-unused/test/vendor/composer-unused/composer-unused-plugin/composer-unused.phar/config/container.php:5
Stack trace:
#0 /Users/andreas.froemer/Projects/composer-unused/test/vendor/composer-unused/composer-unused-plugin/src/UnusedPlugin.php(36): require()
```

**Comment by filipagh** [comment]
<details>
  <summary>Stack trace</summary>

```
  - Installing composer-unused/composer-unused-plugin (0.8.0): Extracting archive
PHP Fatal error:  Uncaught Error: Class "ComposerUnused\ComposerUnused\Di\ServiceContainer" not found in phar:///srv/http/LiveAgent/LiveAgent/server/vendor/composer-unused/composer-unused-plugin/composer-unused.phar/config/container.php:5
Stack trace:
#0 /srv/http/LiveAgent/LiveAgent/server/vendor/composer-unused/composer-unused-plugin/src/UnusedPlugin.php(36): require()
#1 phar:///usr/bin/composer/src/Composer/Plugin/PluginManager.php(411): ComposerUnused\ComposerUnusedPlugin\UnusedPlugin->activate()
#2 phar:///usr/bin/composer/src/Composer/Plugin/PluginManager.php(292): Composer\Plugin\PluginManager->addPlugin()
#3 phar:///usr/bin/composer/src/Composer/Installer/PluginInstaller.php(79): Composer\Plugin\PluginManager->registerPackage()
#4 [internal function]: Composer\Installer\PluginInstaller->Composer\Installer\{closure}()
#5 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func()
#6 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(74): React\Promise\FulfilledPromise->then()
#7 [internal function]: React\Promise\Deferred->React\Promise\{closure}()
#8 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func()
#9 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue()
#10 [internal function]: React\Promise\Deferred->resolve()
#11 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func()
#12 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(76): React\Promise\FulfilledPromise->then()
#13 [internal function]: React\Promise\Deferred->React\Promise\{closure}()
#14 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func()
#15 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue()
#16 [internal function]: React\Promise\Deferred->resolve()
#17 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func()
#18 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(74): React\Promise\FulfilledPromise->then()
#19 [internal function]: React\Promise\Deferred->React\Promise\{closure}()
#20 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func()
#21 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue()
#22 [internal function]: React\Promise\Deferred->resolve()
#23 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func()
#24 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(76): React\Promise\FulfilledPromise->then()
#25 [internal function]: React\Promise\Deferred->React\Promise\{closure}()
#26 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func()
#27 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue()
#28 [internal function]: React\Promise\Deferred->resolve()
#29 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func()
#30 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(76): React\Promise\FulfilledPromise->then()
#31 [internal function]: React\Promise\Deferred->React\Promise\{closure}()
#32 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func()
#33 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue()
#34 [internal function]: React\Promise\Deferred->resolve()
#35 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func()
#36 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(76): React\Promise\FulfilledPromise->then()
#37 [internal function]: React\Promise\Deferred->React\Promise\{closure}()
#38 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func()
#39 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue()
#40 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Promise.php(42): React\Promise\Deferred->resolve()
#41 [internal function]: React\Promise\Promise->React\Promise\{closure}()
#42 phar:///usr/bin/composer/src/Composer/Util/ProcessExecutor.php(343): call_user_func()
#43 phar:///usr/bin/composer/src/Composer/Util/Loop.php(98): Composer\Util\ProcessExecutor->countActiveJobs()
#44 phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php(497): Composer\Util\Loop->wait()
#45 phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php(470): Composer\Installer\InstallationManager->waitOnPromises()
#46 phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php(390): Composer\Installer\InstallationManager->executeBatch()
#47 phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php(282): Composer\Installer\InstallationManager->downloadAndExecuteBatch()
#48 phar:///usr/bin/composer/src/Composer/Installer.php(752): Composer\Installer\InstallationManager->execute()
#49 phar:///usr/bin/composer/src/Composer/Installer.php(582): Composer\Installer->doInstall()
#50 phar:///usr/bin/composer/src/Composer/Installer.php(279): Composer\Installer->doUpdate()
#51 phar:///usr/bin/composer/src/Composer/Command/RequireCommand.php(430): Composer\Installer->run()
#52 phar:///usr/bin/composer/src/Composer/Command/RequireCommand.php(285): Composer\Command\RequireCommand->doUpdate()
#53 phar:///usr/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\RequireCommand->execute()
#54 phar:///usr/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run()
#55 phar:///usr/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand()
#56 phar:///usr/bin/composer/src/Composer/Console/Application.php(335): Symfony\Component\Console\Application->doRun()
#57 phar:///usr/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()
#58 phar:///usr/bin/composer/src/Composer/Console/Application.php(130): Symfony\Component\Console\Application->run()
#59 phar:///usr/bin/composer/bin/composer(73): Composer\Console\Application->run()
#60 /usr/bin/composer(29): require('phar:///usr/bin...')
#61 {main}
  thrown in phar:///srv/http/LiveAgent/LiveAgent/server/vendor/composer-unused/composer-unused-plugin/composer-unused.phar/config/container.php on line 5

Fatal error: Uncaught Error: Class "ComposerUnused\ComposerUnused\Di\ServiceContainer" not found in phar:///srv/http/LiveAgent/LiveAgent/server/vendor/composer-unused/composer-unused-plugin/composer-unused.phar/config/container.php:5
Stack trace:
#0 /srv/http/LiveAgent/LiveAgent/server/vendor/composer-unused/composer-unused-plugin/src/UnusedPlugin.php(36): require()
#1 phar:///usr/bin/composer/src/Composer/Plugin/PluginManager.php(411): ComposerUnused\ComposerUnusedPlugin\UnusedPlugin->activate()
#2 phar:///usr/bin/composer/src/Composer/Plugin/PluginManager.php(292): Composer\Plugin\PluginManager->addPlugin()
#3 phar:///usr/bin/composer/src/Composer/Installer/PluginInstaller.php(79): Composer\Plugin\PluginManager->registerPackage()
#4 [internal function]: Composer\Installer\PluginInstaller->Composer\Installer\{closure}()
#5 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func()
#6 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(74): React\Promise\FulfilledPromise->then()
#7 [internal function]: React\Promise\Deferred->React\Promise\{closure}()
#8 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func()
#9 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue()
#10 [internal function]: React\Promise\Deferred->resolve()
#11 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func()
#12 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(76): React\Promise\FulfilledPromise->then()
#13 [internal function]: React\Promise\Deferred->React\Promise\{closure}()
#14 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func()
#15 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue()
#16 [internal function]: React\Promise\Deferred->resolve()
#17 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func()
#18 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(74): React\Promise\FulfilledPromise->then()
#19 [internal function]: React\Promise\Deferred->React\Promise\{closure}()
#20 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func()
#21 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue()
#22 [internal function]: React\Promise\Deferred->resolve()
#23 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func()
#24 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(76): React\Promise\FulfilledPromise->then()
#25 [internal function]: React\Promise\Deferred->React\Promise\{closure}()
#26 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func()
#27 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue()
#28 [internal function]: React\Promise\Deferred->resolve()
#29 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func()
#30 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(76): React\Promise\FulfilledPromise->then()
#31 [internal function]: React\Promise\Deferred->React\Promise\{closure}()
#32 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func()
#33 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue()
#34 [internal function]: React\Promise\Deferred->resolve()
#35 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func()
#36 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(76): React\Promise\FulfilledPromise->then()
#37 [internal function]: React\Promise\Deferred->React\Promise\{closure}()
#38 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func()
#39 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue()
#40 phar:///usr/bin/composer/vendor/react/promise/src/React/Promise/Promise.php(42): React\Promise\Deferred->resolve()
#41 [internal function]: React\Promise\Promise->React\Promise\{closure}()
#42 phar:///usr/bin/composer/src/Composer/Util/ProcessExecutor.php(343): call_user_func()
#43 phar:///usr/bin/composer/src/Composer/Util/Loop.php(98): Composer\Util\ProcessExecutor->countActiveJobs()
#44 phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php(497): Composer\Util\Loop->wait()
#45 phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php(470): Composer\Installer\InstallationManager->waitOnPromises()
#46 phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php(390): Composer\Installer\InstallationManager->executeBatch()
#47 phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php(282): Composer\Installer\InstallationManager->downloadAndExecuteBatch()
#48 phar:///usr/bin/composer/src/Composer/Installer.php(752): Composer\Installer\InstallationManager->execute()
#49 phar:///usr/bin/composer/src/Composer/Installer.php(582): Composer\Installer->doInstall()
#50 phar:///usr/bin/composer/src/Composer/Installer.php(279): Composer\Installer->doUpdate()
#51 phar:///usr/bin/composer/src/Composer/Command/RequireCommand.php(430): Composer\Installer->run()
#52 phar:///usr/bin/composer/src/Composer/Command/RequireCommand.php(285): Composer\Command\RequireCommand->doUpdate()
#53 phar:///usr/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\RequireCommand->execute()
#54 phar:///usr/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run()
#55 phar:///usr/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand()
#56 phar:///usr/bin/composer/src/Composer/Console/Application.php(335): Symfony\Component\Console\Application->doRun()
#57 phar:///usr/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()
#58 phar:///usr/bin/composer/src/Composer/Console/Application.php(130): Symfony\Component\Console\Application->run()
#59 phar:///usr/bin/composer/bin/composer(73): Composer\Console\Application->run()
#60 /usr/bin/composer(29): require('phar:///usr/bin...')
#61 {main}
  thrown in phar:///srv/http/LiveAgent/LiveAgent/server/vendor/composer-unused/composer-unused-plugin/composer-unused.phar/config/container.php on line 5

```
</details>

**Comment by icanhazstring** [comment]
Useful links:
- https://github.com/phpstan/phpstan-src/blob/master/compiler/build/scoper.inc.php
- https://github.com/phpstan/phpstan/blob/master/bootstrap.php

Current problem is a memory problem with `box-project/box` when having the scoping active.
Need to investigate further.

**Comment by icanhazstring** [comment]
Scope and phar build has been updated. Should investigate if phar usage is now possible

**Comment by icanhazstring** [comment]
Moved to new Issue: #16
