### ISSUE TITLE
Uncaught Error: Class "__ComposerUnused__\Symfony\Component\DependencyInjection\ContainerBuilder" not found

### ISSUE THREAD

**Issue by Hanmac** [composer-unused/composer-unused-plugin#21]
```
  - Installing composer-unused/composer-unused-plugin (0.8.10): Extracting archive
PHP Fatal error:  Uncaught Error: Class "__ComposerUnused__\Symfony\Component\DependencyInjection\ContainerBuilder" not found in phar:///var/www/html/vendor/composer-unused/composer-unused-plugin/composer-unused.phar/config/container.php:10
Stack trace:
#0 phar:///var/www/html/vendor/composer-unused/composer-unused-plugin/composer-unused.phar/config/container.php(18): ComposerUnused\ComposerUnusedPlugin\UnusedPlugin::__ComposerUnused__\{closure}()
#1 /var/www/html/vendor/composer-unused/composer-unused-plugin/src/UnusedPlugin.php(36): require('phar:///var/www...')
#2 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(335): ComposerUnused\ComposerUnusedPlugin\UnusedPlugin->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#3 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(231): Composer\Plugin\PluginManager->addPlugin(Object(ComposerUnused\ComposerUnusedPlugin\UnusedPlugin), false, Object(Composer\Package\CompletePackage))
#4 phar:///usr/local/bin/composer/src/Composer/Installer/PluginInstaller.php(79): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage), true)
#5 [internal function]: Composer\Installer\PluginInstaller->Composer\Installer\{closure}(NULL)
#6 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Object(Closure), NULL)
#7 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(74): React\Promise\FulfilledPromise->then(Object(Closure), NULL)
#8 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#9 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#10 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#11 [internal function]: React\Promise\Deferred->resolve(NULL)
#12 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Array, NULL)
#13 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(76): React\Promise\FulfilledPromise->then(Array, Array, Array)
#14 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#15 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#16 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#17 [internal function]: React\Promise\Deferred->resolve(NULL)
#18 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Array, NULL)
#19 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(74): React\Promise\FulfilledPromise->then(Array, Array)
#20 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#21 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#22 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#23 [internal function]: React\Promise\Deferred->resolve(NULL)
#24 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Array, NULL)
#25 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(76): React\Promise\FulfilledPromise->then(Array, Array, Array)
#26 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#27 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#28 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#29 [internal function]: React\Promise\Deferred->resolve(true)
#30 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Array, true)
#31 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(76): React\Promise\FulfilledPromise->then(Array, Array, Array)
#32 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#33 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#34 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#35 [internal function]: React\Promise\Deferred->resolve(Object(Symfony\Component\Process\Process))
#36 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Array, Object(Symfony\Component\Process\Process))
#37 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(76): React\Promise\FulfilledPromise->then(Array, Array, Array)
#38 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#39 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#40 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#41 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Promise.php(42): React\Promise\Deferred->resolve(Object(Symfony\Component\Process\Process))
#42 [internal function]: React\Promise\Promise->React\Promise\{closure}(Object(Symfony\Component\Process\Process))
#43 phar:///usr/local/bin/composer/src/Composer/Util/ProcessExecutor.php(316): call_user_func(Object(Closure), Object(Symfony\Component\Process\Process))
#44 phar:///usr/local/bin/composer/src/Composer/Util/Loop.php(92): Composer\Util\ProcessExecutor->countActiveJobs()
#45 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(462): Composer\Util\Loop->wait(Array, NULL)
#46 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(440): Composer\Installer\InstallationManager->waitOnPromises(Array)
#47 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(367): Composer\Installer\InstallationManager->executeBatch(Object(Composer\Repository\InstalledFilesystemRepository), Array, Array, true, true, Array)
#48 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(266): Composer\Installer\InstallationManager->downloadAndExecuteBatch(Object(Composer\Repository\InstalledFilesystemRepository), Array, Array, true, true, Array)
#49 phar:///usr/local/bin/composer/src/Composer/Installer.php(706): Composer\Installer\InstallationManager->execute(Object(Composer\Repository\InstalledFilesystemRepository), Array, true, true)
#50 phar:///usr/local/bin/composer/src/Composer/Installer.php(543): Composer\Installer->doInstall(Object(Composer\Repository\InstalledFilesystemRepository), true)
#51 phar:///usr/local/bin/composer/src/Composer/Installer.php(247): Composer\Installer->doUpdate(Object(Composer\Repository\InstalledFilesystemRepository), true)
#52 phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php(241): Composer\Installer->run()
#53 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\UpdateCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#54 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#55 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\UpdateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#56 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(314): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#57 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#58 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(125): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#59 phar:///usr/local/bin/composer/bin/composer(67): Composer\Console\Application->run()
#60 /usr/local/bin/composer(24): require('phar:///usr/loc...')
#61 {main}
  thrown in phar:///var/www/html/vendor/composer-unused/composer-unused-plugin/composer-unused.phar/config/container.php on line 10

Fatal error: Uncaught Error: Class "__ComposerUnused__\Symfony\Component\DependencyInjection\ContainerBuilder" not found in phar:///var/www/html/vendor/composer-unused/composer-unused-plugin/composer-unused.phar/config/container.php:10
Stack trace:
#0 phar:///var/www/html/vendor/composer-unused/composer-unused-plugin/composer-unused.phar/config/container.php(18): ComposerUnused\ComposerUnusedPlugin\UnusedPlugin::__ComposerUnused__\{closure}()
#1 /var/www/html/vendor/composer-unused/composer-unused-plugin/src/UnusedPlugin.php(36): require('phar:///var/www...')
#2 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(335): ComposerUnused\ComposerUnusedPlugin\UnusedPlugin->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#3 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(231): Composer\Plugin\PluginManager->addPlugin(Object(ComposerUnused\ComposerUnusedPlugin\UnusedPlugin), false, Object(Composer\Package\CompletePackage))
#4 phar:///usr/local/bin/composer/src/Composer/Installer/PluginInstaller.php(79): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage), true)
#5 [internal function]: Composer\Installer\PluginInstaller->Composer\Installer\{closure}(NULL)
#6 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Object(Closure), NULL)
#7 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(74): React\Promise\FulfilledPromise->then(Object(Closure), NULL)
#8 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#9 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#10 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#11 [internal function]: React\Promise\Deferred->resolve(NULL)
#12 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Array, NULL)
#13 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(76): React\Promise\FulfilledPromise->then(Array, Array, Array)
#14 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#15 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#16 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#17 [internal function]: React\Promise\Deferred->resolve(NULL)
#18 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Array, NULL)
#19 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(74): React\Promise\FulfilledPromise->then(Array, Array)
#20 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#21 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#22 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#23 [internal function]: React\Promise\Deferred->resolve(NULL)
#24 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Array, NULL)
#25 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(76): React\Promise\FulfilledPromise->then(Array, Array, Array)
#26 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#27 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#28 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#29 [internal function]: React\Promise\Deferred->resolve(true)
#30 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Array, true)
#31 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(76): React\Promise\FulfilledPromise->then(Array, Array, Array)
#32 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#33 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#34 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#35 [internal function]: React\Promise\Deferred->resolve(Object(Symfony\Component\Process\Process))
#36 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Array, Object(Symfony\Component\Process\Process))
#37 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(76): React\Promise\FulfilledPromise->then(Array, Array, Array)
#38 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#39 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#40 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#41 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Promise.php(42): React\Promise\Deferred->resolve(Object(Symfony\Component\Process\Process))
#42 [internal function]: React\Promise\Promise->React\Promise\{closure}(Object(Symfony\Component\Process\Process))
#43 phar:///usr/local/bin/composer/src/Composer/Util/ProcessExecutor.php(316): call_user_func(Object(Closure), Object(Symfony\Component\Process\Process))
#44 phar:///usr/local/bin/composer/src/Composer/Util/Loop.php(92): Composer\Util\ProcessExecutor->countActiveJobs()
#45 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(462): Composer\Util\Loop->wait(Array, NULL)
#46 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(440): Composer\Installer\InstallationManager->waitOnPromises(Array)
#47 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(367): Composer\Installer\InstallationManager->executeBatch(Object(Composer\Repository\InstalledFilesystemRepository), Array, Array, true, true, Array)
#48 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(266): Composer\Installer\InstallationManager->downloadAndExecuteBatch(Object(Composer\Repository\InstalledFilesystemRepository), Array, Array, true, true, Array)
#49 phar:///usr/local/bin/composer/src/Composer/Installer.php(706): Composer\Installer\InstallationManager->execute(Object(Composer\Repository\InstalledFilesystemRepository), Array, true, true)
#50 phar:///usr/local/bin/composer/src/Composer/Installer.php(543): Composer\Installer->doInstall(Object(Composer\Repository\InstalledFilesystemRepository), true)
#51 phar:///usr/local/bin/composer/src/Composer/Installer.php(247): Composer\Installer->doUpdate(Object(Composer\Repository\InstalledFilesystemRepository), true)
#52 phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php(241): Composer\Installer->run()
#53 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\UpdateCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#54 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#55 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\UpdateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#56 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(314): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#57 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#58 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(125): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#59 phar:///usr/local/bin/composer/bin/composer(67): Composer\Console\Application->run()
#60 /usr/local/bin/composer(24): require('phar:///usr/loc...')
#61 {main}
  thrown in phar:///var/www/html/vendor/composer-unused/composer-unused-plugin/composer-unused.phar/config/container.php on line 10
```

_Originally posted by @Hanmac in https://github.com/composer-unused/composer-unused/issues/451#issuecomment-1678838732_

**Comment by Wirone** [comment]
I can confirm the problem:

```
composer require --dev composer-unused/composer-unused-plugin
./composer.json has been updated
Running composer update composer-unused/composer-unused-plugin
Loading composer repositories with package information
Updating dependencies
Lock file operations: 7 installs, 0 updates, 0 removals
  - Locking composer-unused/composer-unused-plugin (0.8.11)
  - Locking composer-unused/contracts (0.3.0)
  - Locking composer-unused/symbol-parser (0.2.5)
  - Locking icanhazstring/composer-unused (0.8.11)
  - Locking ondram/ci-detector (4.2.0)
  - Locking symfony/validator (v7.1.1)
  - Locking webmozart/glob (4.7.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 7 installs, 0 updates, 0 removals
  - Downloading composer-unused/composer-unused-plugin (0.8.11)
  - Installing webmozart/glob (4.7.0): Extracting archive
  - Installing symfony/validator (v7.1.1): Extracting archive
  - Installing ondram/ci-detector (4.2.0): Extracting archive
  - Installing composer-unused/contracts (0.3.0): Extracting archive
  - Installing composer-unused/symbol-parser (0.2.5): Extracting archive
  - Installing icanhazstring/composer-unused (0.8.11): Extracting archive
composer-unused/composer-unused-plugin contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Do you trust "composer-unused/composer-unused-plugin" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] y
  - Installing composer-unused/composer-unused-plugin (0.8.11): Extracting archive
    Install of composer-unused/composer-unused-plugin failed

In container.php line 10:
                                                                                               
  [Error]                                                                                      
  Class "__ComposerUnused__\Symfony\Component\DependencyInjection\ContainerBuilder" not found  
                                                                                               

Exception trace:
  at phar:///.../vendor/composer-unused/composer-unused-plugin/composer-unused.phar/config/container.php:10
 ComposerUnused\ComposerUnusedPlugin\UnusedPlugin::__ComposerUnused__\{closure}() at phar:///.../vendor/composer-unused/composer-unused-plugin/composer-unused.phar/config/container.php:18
 require() at /.../vendor/composer-unused/composer-unused-plugin/src/UnusedPlugin.php:36
 ComposerUnused\ComposerUnusedPlugin\UnusedPlugin->activate() at phar:///.../composer/src/Composer/Plugin/PluginManager.php:392
 Composer\Plugin\PluginManager->addPlugin() at phar:///.../composer/src/Composer/Plugin/PluginManager.php:296
 Composer\Plugin\PluginManager->registerPackage() at phar:///.../composer/src/Composer/Installer/PluginInstaller.php:90
```

😭

**Comment by DannyvdSluijs** [comment]
I can confirm the same btu can add more details about the env and an alternative approach

My environment:
```
PHP 8.3
Symfony 6.4.15
```

My steps to get it working
- Install using the documented approach `composer require composer-unused/composer-unused-plugin`
- Confirm the question: `Do you trust "composer-unused/composer-unused-plugin" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json)`
- The install fails with the error `Class "__ComposerUnused__\Symfony\Component\DependencyInjection\ContainerBuilder" not found `
- Running `php ./vendor/composer-unused/composer-unused-plugin/composer-unused.phar` works and I get an expected output.
```bash
Results
-------

Found 50 used, 25 unused, 1 ignored and 0 zombie packages

<REDACTED>

 Ignored packages
 ○ composer-unused/composer-unused-plugin (ignored by NamedFilter(userProvided: false, string: composer-unused/composer-unused-plugin))

 Zombies exclusions (did not match any package)
```
